# Generated by Django 5.1.5 on 2025-01-22 01:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('Id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Base64', models.TextField()),
            ],
            options={
                'db_table': 'photos',
            },
        ),
    ]
