# Generated by Django 5.1.5 on 2025-01-22 03:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='Base64',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='Id',
        ),
        migrations.AddField(
            model_name='photo',
            name='base64',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
