# Generated by Django 5.1.5 on 2025-01-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_remove_photo_base64_remove_photo_id_photo_base64_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='base64',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
