# Generated by Django 5.1.5 on 2025-01-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_alter_photo_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='base64',
            field=models.TextField(),
        ),
    ]
