# Generated by Django 5.1.5 on 2025-01-22 14:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('SOLD', 'Vendido'), ('AVAILABLE', 'Disponível')], db_index=True, default='AVAILABLE')),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.photo')),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
